# Generated by Django 4.2.23 on 2025-12-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SeatDestID", models.CharField(max_length=50, unique=True)),
                ("Available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SeatBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Booker_Email", models.EmailField(max_length=254)),
                ("Reason", models.TextField(blank=True)),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("Pending approval", "Pending approval"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending approval",
                        max_length=20,
                    ),
                ),
                (
                    "Departure_Seat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="departure_bookings",
                        to="bookings.seat",
                    ),
                ),
                (
                    "Return_Seat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_bookings",
                        to="bookings.seat",
                    ),
                ),
            ],
        ),
    ]
