# Generated by Django 4.2.23 on 2025-12-26 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "car_registration",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("car_type", models.CharField(max_length=50)),
                ("capacity", models.IntegerField()),
                (
                    "available",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")], default="Y", max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_email", models.EmailField(max_length=254)),
                ("passengers", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending approval", "Pending approval"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending approval",
                        max_length=20,
                    ),
                ),
                (
                    "car_registration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bookings.car",
                    ),
                ),
            ],
        ),
    ]
